# Generated by Django 6.0.5 on 2026-07-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpush', '0005_auto_20230614_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
