# Generated by Django 6.0.5 on 2026-05-08 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(choices=[('Vijayanagar', 'Vijayanagar'), ('Gokulam', 'Gokulam'), ('Kuvempunagar', 'Kuvempunagar'), ('Saraswathipuram', 'Saraswathipuram'), ('Jayalakshmipuram', 'Jayalakshmipuram'), ('Vontikoppal', 'Vontikoppal'), ('Hebbal', 'Hebbal'), ('Bannimantap', 'Bannimantap'), ('Bogadi', 'Bogadi'), ('Siddhartha Layout', 'Siddhartha Layout'), ('Other (Mysore)', 'Other (Mysore)')], default='Vijayanagar', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('type', models.CharField(choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('Single Room', 'Single Room'), ('PG (Men)', 'PG (Men)'), ('PG (Women)', 'PG (Women)'), ('Co-living', 'Co-living'), ('Flatmate', 'Flatmate'), ('Commercial Space', 'Commercial Space'), ('Office Space', 'Office Space')], max_length=20)),
                ('available_from', models.CharField(default='Immediately', max_length=100)),
                ('food_preference', models.CharField(choices=[('Any', 'Any'), ('Veg Only', 'Veg Only'), ('Non-Veg Allowed', 'Non-Veg Allowed')], default='Any', max_length=20)),
                ('curfew', models.CharField(choices=[('No Curfew', 'No Curfew'), ('9 PM', '9 PM'), ('10 PM', '10 PM'), ('11 PM', '11 PM'), ('Strict', 'Strict')], default='No Curfew', max_length=20)),
                ('visitors', models.CharField(choices=[('Allowed', 'Allowed'), ('Not Allowed', 'Not Allowed'), ('Daytime Only', 'Daytime Only')], default='Allowed', max_length=20)),
                ('landmark', models.CharField(blank=True, default='', help_text='e.g. 5 mins from JSS College', max_length=200)),
                ('description', models.TextField()),
                ('facilities', models.CharField(help_text='Comma separated e.g. WiFi, Food, AC, Parking', max_length=200)),
                ('image', models.ImageField(upload_to='listings/')),
                ('address', models.TextField(default='')),
                ('exact_location', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=20)),
                ('is_sold', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('listing_purpose', models.CharField(default='Rent', max_length=20)),
                ('rooms_available', models.IntegerField(default=1)),
                ('sharing_count', models.IntegerField(default=1)),
                ('flatmate_preference', models.CharField(blank=True, default='', max_length=50)),
                ('commercial_type', models.CharField(blank=True, default='', max_length=50)),
                ('built_up_area', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/gallery/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('listing', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
