# Generated by Django 6.0.5 on 2026-05-08 20:50

from django.db import migrations, models

def add_column_if_not_exists(table_name, column_name, field_def):
    def inner(apps, schema_editor):
        connection = schema_editor.connection
        with connection.cursor() as cursor:
            if connection.vendor == 'postgresql':
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT 1 
                        FROM pg_attribute 
                        WHERE attrelid = to_regclass(%s) 
                        AND attname = %s
                    )
                """, [table_name, column_name])
                col_exists = cursor.fetchone()[0]
            else:
                cursor.execute(f"PRAGMA table_info({table_name})")
                columns = [row[1] for row in cursor.fetchall()]
                col_exists = column_name in columns
                
        if not col_exists:
            model = apps.get_model('listings', 'Listing')
            schema_editor.add_field(model, field_def)
    return inner

class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[
                migrations.RunPython(
                    add_column_if_not_exists('listings_listing', 'views_count', models.IntegerField(default=0)),
                    reverse_code=migrations.RunPython.noop
                ),
                migrations.RunPython(
                    add_column_if_not_exists('listings_listing', 'built_up_area', models.CharField(blank=True, default='', max_length=50)),
                    reverse_code=migrations.RunPython.noop
                ),
                migrations.RunPython(
                    add_column_if_not_exists('listings_listing', 'commercial_type', models.CharField(blank=True, default='', max_length=50)),
                    reverse_code=migrations.RunPython.noop
                ),
                migrations.RunPython(
                    add_column_if_not_exists('listings_listing', 'flatmate_preference', models.CharField(blank=True, default='', max_length=50)),
                    reverse_code=migrations.RunPython.noop
                ),
                migrations.RunPython(
                    add_column_if_not_exists('listings_listing', 'listing_purpose', models.CharField(default='Rent', max_length=20)),
                    reverse_code=migrations.RunPython.noop
                ),
                migrations.RunPython(
                    add_column_if_not_exists('listings_listing', 'rooms_available', models.IntegerField(default=1)),
                    reverse_code=migrations.RunPython.noop
                ),
                migrations.RunPython(
                    add_column_if_not_exists('listings_listing', 'sharing_count', models.IntegerField(default=1)),
                    reverse_code=migrations.RunPython.noop
                ),
                migrations.RunPython(
                    add_column_if_not_exists('listings_listing', 'available_from', models.CharField(default='Immediately', max_length=100)),
                    reverse_code=migrations.RunPython.noop
                ),
                migrations.RunPython(
                    add_column_if_not_exists('listings_listing', 'curfew', models.CharField(choices=[('No Curfew', 'No Curfew'), ('9 PM', '9 PM'), ('10 PM', '10 PM'), ('11 PM', '11 PM'), ('Strict', 'Strict')], default='No Curfew', max_length=20)),
                    reverse_code=migrations.RunPython.noop
                ),
                migrations.RunPython(
                    add_column_if_not_exists('listings_listing', 'deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                    reverse_code=migrations.RunPython.noop
                ),
                migrations.RunPython(
                    add_column_if_not_exists('listings_listing', 'food_preference', models.CharField(choices=[('Any', 'Any'), ('Veg Only', 'Veg Only'), ('Non-Veg Allowed', 'Non-Veg Allowed')], default='Any', max_length=20)),
                    reverse_code=migrations.RunPython.noop
                ),
                migrations.RunPython(
                    add_column_if_not_exists('listings_listing', 'landmark', models.CharField(blank=True, default='', help_text='e.g. 5 mins from JSS College', max_length=200)),
                    reverse_code=migrations.RunPython.noop
                ),
                migrations.RunPython(
                    add_column_if_not_exists('listings_listing', 'visitors', models.CharField(choices=[('Allowed', 'Allowed'), ('Not Allowed', 'Not Allowed'), ('Daytime Only', 'Daytime Only')], default='Allowed', max_length=20)),
                    reverse_code=migrations.RunPython.noop
                ),
            ]
        )
    ]
