# Generated by Django 6.0.5 on 2026-05-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='built_up_area',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='commercial_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='flatmate_preference',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_purpose',
            field=models.CharField(default='Rent', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='rooms_available',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='sharing_count',
            field=models.IntegerField(default=1),
        ),
    ]
