# Generated by Django 6.0.5 on 2026-05-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_built_up_area_listing_commercial_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='whatsapp_clicks_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
