# Generated by Django 6.0.5 on 2026-05-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_exact_location_listingimage_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(choices=[('Vijayanagar', 'Vijayanagar'), ('Gokulam', 'Gokulam'), ('Kuvempunagar', 'Kuvempunagar'), ('Saraswathipuram', 'Saraswathipuram'), ('Jayalakshmipuram', 'Jayalakshmipuram'), ('Vontikoppal', 'Vontikoppal'), ('Hebbal', 'Hebbal'), ('Bannimantap', 'Bannimantap'), ('Bogadi', 'Bogadi'), ('Siddhartha Layout', 'Siddhartha Layout'), ('Other (Mysore)', 'Other (Mysore)')], default='Vijayanagar', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('Single Room', 'Single Room'), ('PG (Men)', 'PG (Men)'), ('PG (Women)', 'PG (Women)'), ('Co-living', 'Co-living')], max_length=20),
        ),
    ]
