# Generated by Django 6.0.5 on 2026-05-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_views_count_listing_whatsapp_clicks_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='target_gender',
            field=models.CharField(choices=[('Any', 'Any (Boys or Girls)'), ('Boys Only', 'Boys Only'), ('Girls Only', 'Girls Only')], default='Any', max_length=20),
        ),
    ]
