# Generated by Django 6.0.5 on 2026-05-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_target_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='furnishing',
            field=models.CharField(choices=[('Unfurnished', 'Unfurnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Fully Furnished', 'Fully Furnished')], default='Unfurnished', max_length=20),
        ),
    ]
