# Generated by Django 6.0.5 on 2026-05-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_furnishing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(choices=[('Vijayanagar', 'Vijayanagar'), ('Gokulam', 'Gokulam'), ('Kuvempunagar', 'Kuvempunagar'), ('Saraswathipuram', 'Saraswathipuram'), ('Jayalakshmipuram', 'Jayalakshmipuram'), ('Vontikoppal', 'Vontikoppal'), ('Hebbal', 'Hebbal'), ('Bannimantap', 'Bannimantap'), ('Bogadi', 'Bogadi'), ('Siddhartha Layout', 'Siddhartha Layout'), ('Padvarahalli', 'Padvarahalli'), ('Vinayakanagar', 'Vinayakanagar'), ('Other (Mysore)', 'Other (Mysore)')], default='Vijayanagar', max_length=50),
        ),
    ]
