# Generated by Django 6.0.5 on 2026-05-06 19:36

from django.db import migrations, models

def add_field_if_not_exists(table_name, column_name):
    def inner(apps, schema_editor):
        connection = schema_editor.connection
        with connection.cursor() as cursor:
            if connection.vendor == 'postgresql':
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT 1 
                        FROM pg_attribute 
                        WHERE attrelid = to_regclass(%s) 
                        AND attname = %s
                    )
                """, [table_name, column_name])
                exists = cursor.fetchone()[0]
            else:
                cursor.execute(f"PRAGMA table_info({table_name})")
                columns = [row[1] for row in cursor.fetchall()]
                exists = column_name in columns
                
        if not exists:
            model = apps.get_model('listings', 'Listing')
            field = model._meta.get_field(column_name)
            schema_editor.add_field(model, field)
    return inner

class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_review'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='listing',
                    name='available_from',
                    field=models.CharField(default='Immediately', max_length=100),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_field_if_not_exists('listings_listing', 'available_from'),
                    reverse_code=migrations.RunPython.noop
                )
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='listing',
                    name='curfew',
                    field=models.CharField(choices=[('No Curfew', 'No Curfew'), ('9 PM', '9 PM'), ('10 PM', '10 PM'), ('11 PM', '11 PM'), ('Strict', 'Strict')], default='No Curfew', max_length=20),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_field_if_not_exists('listings_listing', 'curfew'),
                    reverse_code=migrations.RunPython.noop
                )
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='listing',
                    name='deposit',
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_field_if_not_exists('listings_listing', 'deposit'),
                    reverse_code=migrations.RunPython.noop
                )
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='listing',
                    name='food_preference',
                    field=models.CharField(choices=[('Any', 'Any'), ('Veg Only', 'Veg Only'), ('Non-Veg Allowed', 'Non-Veg Allowed')], default='Any', max_length=20),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_field_if_not_exists('listings_listing', 'food_preference'),
                    reverse_code=migrations.RunPython.noop
                )
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='listing',
                    name='landmark',
                    field=models.CharField(blank=True, default='', help_text='e.g. 5 mins from JSS College', max_length=200),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_field_if_not_exists('listings_listing', 'landmark'),
                    reverse_code=migrations.RunPython.noop
                )
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='listing',
                    name='visitors',
                    field=models.CharField(choices=[('Allowed', 'Allowed'), ('Not Allowed', 'Not Allowed'), ('Daytime Only', 'Daytime Only')], default='Allowed', max_length=20),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_field_if_not_exists('listings_listing', 'visitors'),
                    reverse_code=migrations.RunPython.noop
                )
            ]
        ),
    ]
