# Generated by Django 6.0.5 on 2026-05-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='nearby_food_options',
            field=models.CharField(blank=True, default='', help_text='List nearby mess, tiffin services, or restaurants', max_length=255),
        ),
    ]
