# Generated by Django 4.2.13 on 2026-06-22 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0007_listing_nearby_food_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified by RoomNest admin'),
        ),
        migrations.AddField(
            model_name='listing',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='verification_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='verification_status',
            field=models.CharField(choices=[('Not Requested', 'Not Requested'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Not Requested', max_length=20),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message_content', models.TextField(blank=True, default='')),
                ('lead_type', models.CharField(choices=[('WhatsApp', 'WhatsApp Inquiry'), ('Chat', 'Direct Chat Message')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='listings.listing')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
