# Generated by Django 4.2.13 on 2026-06-25 19:10

from django.db import migrations

def populate_cities_and_areas(apps, schema_editor):
    City = apps.get_model('listings', 'City')
    Area = apps.get_model('listings', 'Area')
    Listing = apps.get_model('listings', 'Listing')

    # 1. Create launch cities
    mysore = City.objects.create(
        name="Mysore", 
        slug="mysore", 
        description="Find verified rental properties, PGs and rooms in Mysore with zero brokerage and direct owner contact."
    )
    bengaluru = City.objects.create(
        name="Bengaluru", 
        slug="bengaluru", 
        description="Find verified rental properties, PGs and rooms in Bengaluru with zero brokerage and direct owner contact."
    )
    hyderabad = City.objects.create(
        name="Hyderabad", 
        slug="hyderabad", 
        description="Find verified rental properties, PGs and rooms in Hyderabad with zero brokerage and direct owner contact."
    )

    # 2. Create Mysore Areas
    mysore_areas = [
        ("Vijayanagar", "vijayanagar"),
        ("Gokulam", "gokulam"),
        ("Kuvempunagar", "kuvempu-nagar"),
        ("Saraswathipuram", "saraswathipuram"),
        ("Jayalakshmipuram", "jayalakshmipuram"),
        ("Vontikoppal", "vontikoppal"),
        ("Hebbal", "hebbal"),
        ("Bannimantap", "bannimantap"),
        ("Bogadi", "bogadi"),
        ("Siddhartha Layout", "siddhartha-layout"),
        ("Padvarahalli", "padvarahalli"),
        ("Vinayakanagar", "vinayakanagar"),
        ("Other (Mysore)", "other-mysore"),
    ]
    for name, slug in mysore_areas:
        Area.objects.create(city=mysore, name=name, slug=slug)

    # 3. Create Bengaluru Areas
    bengaluru_areas = [
        ("Whitefield", "whitefield"),
        ("HSR Layout", "hsr-layout"),
        ("Electronic City", "electronic-city"),
        ("Indiranagar", "indiranagar"),
        ("Koramangala", "koramangala"),
        ("Jayanagar", "jayanagar"),
    ]
    for name, slug in bengaluru_areas:
        Area.objects.create(city=bengaluru, name=name, slug=slug)

    # 4. Create Hyderabad Areas
    hyderabad_areas = [
        ("Gachibowli", "gachibowli"),
        ("Madhapur", "madhapur"),
        ("Kondapur", "kondapur"),
        ("Banjara Hills", "banjara-hills"),
        ("Jubilee Hills", "jubilee-hills"),
        ("Kukatpally", "kukatpally"),
    ]
    for name, slug in hyderabad_areas:
        Area.objects.create(city=hyderabad, name=name, slug=slug)

    # 5. Migrate existing listings to Mysore and their correct areas
    all_mysore_areas = list(Area.objects.filter(city=mysore))
    other_mysore_area = Area.objects.get(city=mysore, slug='other-mysore')

    for listing in Listing.objects.all():
        listing.city = mysore
        
        # Robust normalization matching to locate the correct area
        loc_str = str(listing.location).strip()
        normalized = loc_str.lower().replace(' ', '').replace('-', '')
        
        matching_area = None
        for area in all_mysore_areas:
            area_name_norm = area.name.lower().replace(' ', '').replace('-', '')
            area_slug_norm = area.slug.replace('-', '')
            if normalized == area_name_norm or normalized == area_slug_norm:
                matching_area = area
                break
        
        if not matching_area:
            matching_area = other_mysore_area
            
        listing.area = matching_area
        listing.save()

def rollback_cities_and_areas(apps, schema_editor):
    # Dropping tables in 0010 makes rollback clean automatically,
    # but we provide a pass function to make the migration reversible.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_city_area_listing_area_listing_city_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_cities_and_areas, rollback_cities_and_areas),
    ]
