# Generated by Django 6.0.5 on 2026-05-08 20:01

from django.db import migrations, models

def add_field_if_not_exists(table_name, column_name):
    def inner(apps, schema_editor):
        connection = schema_editor.connection
        with connection.cursor() as cursor:
            if connection.vendor == 'postgresql':
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT 1 
                        FROM pg_attribute 
                        WHERE attrelid = to_regclass(%s) 
                        AND attname = %s
                    )
                """, [table_name, column_name])
                exists = cursor.fetchone()[0]
            else:
                cursor.execute(f"PRAGMA table_info({table_name})")
                columns = [row[1] for row in cursor.fetchall()]
                exists = column_name in columns
                
        if not exists:
            model = apps.get_model('listings', 'Listing')
            field = model._meta.get_field(column_name)
            schema_editor.add_field(model, field)
    return inner

class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_remove_listing_views_count'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='listing',
                    name='built_up_area',
                    field=models.CharField(blank=True, default='', max_length=50),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_field_if_not_exists('listings_listing', 'built_up_area'),
                    reverse_code=migrations.RunPython.noop
                )
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='listing',
                    name='commercial_type',
                    field=models.CharField(blank=True, default='', max_length=50),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_field_if_not_exists('listings_listing', 'commercial_type'),
                    reverse_code=migrations.RunPython.noop
                )
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='listing',
                    name='flatmate_preference',
                    field=models.CharField(blank=True, default='', max_length=50),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_field_if_not_exists('listings_listing', 'flatmate_preference'),
                    reverse_code=migrations.RunPython.noop
                )
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='listing',
                    name='listing_purpose',
                    field=models.CharField(default='Rent', max_length=20),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_field_if_not_exists('listings_listing', 'listing_purpose'),
                    reverse_code=migrations.RunPython.noop
                )
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='listing',
                    name='rooms_available',
                    field=models.IntegerField(default=1),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_field_if_not_exists('listings_listing', 'rooms_available'),
                    reverse_code=migrations.RunPython.noop
                )
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='listing',
                    name='sharing_count',
                    field=models.IntegerField(default=1),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_field_if_not_exists('listings_listing', 'sharing_count'),
                    reverse_code=migrations.RunPython.noop
                )
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='listing',
                    name='views_count',
                    field=models.IntegerField(default=0),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_field_if_not_exists('listings_listing', 'views_count'),
                    reverse_code=migrations.RunPython.noop
                )
            ]
        ),
    ]
