# Generated by Django 4.2.13 on 2026-07-01 15:48

from django.db import migrations, models

def populate_existing_data(apps, schema_editor):
    from django.utils.text import slugify
    City = apps.get_model('listings', 'City')
    Area = apps.get_model('listings', 'Area')
    Listing = apps.get_model('listings', 'Listing')
    
    # Ensure Hitech City exists in Hyderabad
    hyderabad = City.objects.filter(slug='hyderabad').first()
    if hyderabad:
        Area.objects.get_or_create(city=hyderabad, slug='hitech-city', defaults={'name': 'Hitech City', 'is_active': True})

    # Generate slugs for all listings
    for listing in Listing.objects.all():
        if not listing.slug:
            type_str = listing.type.lower()
            if 'pg' in type_str:
                if 'men' in type_str or listing.target_gender == 'Boys Only':
                    type_slug = 'pg-for-boys'
                elif 'women' in type_str or listing.target_gender == 'Girls Only':
                    type_slug = 'pg-for-girls'
                else:
                    type_slug = 'pg'
            elif '1bhk' in type_str:
                type_slug = '1-bhk-room'
            elif '2bhk' in type_str:
                type_slug = '2-bhk-flat'
            elif '3bhk' in type_str:
                type_slug = '3-bhk-flat'
            elif 'flatmate' in type_str:
                type_slug = 'flatmate-room'
            elif 'co-living' in type_str:
                type_slug = 'co-living-space'
            else:
                type_slug = slugify(listing.type)
                
            purpose_slug = slugify(listing.listing_purpose or 'rent')
            area_name = listing.area.name if listing.area else (listing.location or '')
            area_slug = slugify(area_name)
            
            parts = []
            if 'pg' in type_slug:
                parts.append(type_slug)
            else:
                parts.append(type_slug)
                parts.append(f"for-{purpose_slug}")
            if area_slug:
                parts.append(area_slug)
                
            base_slug = '-'.join(parts)
            slug = base_slug
            counter = 1
            while Listing.objects.filter(city=listing.city, slug=slug).exclude(id=listing.id).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            listing.slug = slug
            listing.save()


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_listing_google_place_id_listing_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city', 'slug'], name='listings_li_city_id_0f2bd4_idx'),
        ),
        migrations.RunPython(populate_existing_data, reverse_code=migrations.RunPython.noop),
    ]
