# Generated by Django 4.2.13 on 2026-07-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_listing_slug_listing_listings_li_city_id_0f2bd4_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='nearby_landmarks_cache',
            field=models.TextField(blank=True, default=''),
        ),
    ]
