# Generated by Django 6.0.5 on 2026-05-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin verified owner badge'),
        ),
    ]
