# Generated by Django 6.0.5 on 2026-05-08 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def create_or_sync_table(table_name, model_name, fields):
    def inner(apps, schema_editor):
        connection = schema_editor.connection
        with connection.cursor() as cursor:
            if connection.vendor == 'postgresql':
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT 1 
                        FROM information_schema.tables 
                        WHERE table_schema = 'public' 
                        AND table_name = %s
                    )
                """, [table_name])
                table_exists = cursor.fetchone()[0]
            else:
                cursor.execute(f"SELECT name FROM sqlite_master WHERE type='table' AND name='{table_name}'")
                table_exists = len(cursor.fetchall()) > 0
                
        model = apps.get_model('subscriptions', model_name)
        
        if not table_exists:
            schema_editor.create_model(model)
        else:
            for field_name in fields:
                field = model._meta.get_field(field_name)
                column_name = field.column
                with connection.cursor() as cursor:
                    if connection.vendor == 'postgresql':
                        cursor.execute("""
                            SELECT EXISTS (
                                SELECT 1 
                                FROM pg_attribute 
                                WHERE attrelid = to_regclass(%s) 
                                AND attname = %s
                            )
                        """, [table_name, column_name])
                        col_exists = cursor.fetchone()[0]
                    else:
                        cursor.execute(f"PRAGMA table_info({table_name})")
                        columns = [row[1] for row in cursor.fetchall()]
                        col_exists = column_name in columns
                        
                if not col_exists:
                    schema_editor.add_field(model, field)
    return inner

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Subscription',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('is_active', models.BooleanField(default=False)),
                        ('start_date', models.DateTimeField(auto_now_add=True)),
                        ('end_date', models.DateTimeField()),
                        ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                        ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    create_or_sync_table('subscriptions_subscription', 'Subscription', [
                        'id', 'is_active', 'start_date', 'end_date', 'transaction_id', 'payment_status', 'user'
                    ]),
                    reverse_code=migrations.RunPython.noop
                )
            ]
        )
    ]
