# Generated by Django 4.2.13 on 2026-06-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_name',
            field=models.CharField(default='90 Days Premium', max_length=50),
        ),
    ]
